name: paper-maker

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LATEX: pdflatex -shell-escape
      BIBTEX: bibtex
    steps:
    - uses: actions/checkout@v1
    - name: Install texlive
      run: |
        sudo apt-get install texlive-publishers \
                             texlive-latex-recommended \
                             texlive-latex-extra \
                             texlive-fonts-recommended \
                             texlive-fonts-extra \
                             texlive-science
    - name: Build paper
      run: |
        ${LATEX} *.tex
        ${BIBTEX} *.aux
        ${LATEX} *.tex
        ${LATEX} *.tex


    - name: Push paper
      run: |
        git checkout --orphan ${GITHUB_REF##*/}-pdf
        git add -f thesis.pdf
        git add -f thesis.log
        git -c user.name='paper-maker' -c user.email='paper-maker' commit -m "update pdf at https://github.com/${{ github.repository }}/blob/${GITHUB_REF##*/}-pdf/ms.pdf"
        git push -q -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${GITHUB_REF##*/}-pdf
